### PR TITLE
🐛 fix centerpiece not being an overlay in some wayland WMs

### LINKED ISSUE #188: Integrate with wlr layershell to properly support floating in wayland
Instead of using the default implementation of floating within iced, we should switch to layershell: https://crates.io/crates/iced-layershell. layershell is wayland protocol which should be used for things like floating.

### PR DESCRIPTION
**Pull request by friedow**
This PR fixes a bug where centerpiece was treated as a normal window and not a popup in some wayland window managers like [Niri](https://github.com/YaLTeR/niri). This was fixed by introducing [iced_layershell](https://crates.io/crates/iced-layershell) as a dependency which implements the [wayland layershell protocol](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) for iced.

We had to revert the builder pattern for the iced application which was introduced with the upgrade to iced 0.13.x because iced_layershell does not support that yet.

Special thanks to @Decodetalkers for jumping in and helping me make this happen.

This resolves #188.

### CODE REVIEW

**Comment by Decodetalkers** [comment]
Should the keyboard_interactivity be set to Exclusive to always focus on this program?

File: client/src/main.rs [hunk 1]
```diff
@@ -324,6 +327,13 @@ fn settings() -> iced::Settings {
             style: iced::font::Style::default(),
         },
         default_text_size: iced::Pixels(crate::REM),
+        layer_settings: iced_layershell::settings::LayerShellSettings {
+            size: Some((650, 380)),
+            layer: iced_layershell::reexport::Layer::Top,
+            anchor: iced_layershell::reexport::Anchor::Top,
+            margin: (200, 0, 0, 0),
```
Comment (Decodetalkers) [inline client/src/main.rs:334]:
```
keyboard_interactivity: iced_layershell::reexport::KeyboardInteractivity::Exclusive
```

maybe add this setting will be better I think
